modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "${mod_issue_url}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayURL = "${mod_url}"
description = '''${mod_description}'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="${create_forge_version}"
ordering="NONE"
side="BOTH"